<?php

return [
    'breadcrumb' => ['home' => 'Catering', 'list' => 'Employees', 'create' => 'Add employee', 'edit' => 'Edit employee'],
    'navigation' => 'Employees', 'group' => 'HUMAN RESOURCES', 'create_title' => 'Add employee', 'edit_title' => 'Edit employee',
    'create_description' => 'Enter information to create a new employee profile', 'edit_description' => 'Update employee information and records',
    'sections' => ['avatar' => 'Profile image', 'personal' => 'Personal information', 'work' => 'Employment information', 'address' => 'Address & emergency contact', 'documents' => 'Attached documents'],
    'fields' => ['name' => 'Full name', 'code' => 'Employee code', 'gender' => 'Gender', 'birth_date' => 'Date of birth', 'identity_number' => 'ID / Passport number', 'phone' => 'Phone number', 'email' => 'Email', 'department' => 'Department', 'position' => 'Position / Title', 'area' => 'Work area', 'kitchen' => 'Assigned kitchen', 'start_date' => 'Start date', 'status' => 'Status', 'avatar' => 'Profile image', 'issue_date' => 'Issue date', 'issue_place' => 'Place of issue', 'marital_status' => 'Marital status', 'nationality' => 'Nationality', 'ethnicity' => 'Ethnicity', 'religion' => 'Religion', 'permanent_address' => 'Permanent address', 'temporary_address' => 'Temporary address', 'emergency_contact' => 'Emergency contact', 'emergency_phone' => 'Emergency phone'],
    'placeholders' => ['name' => 'E.g. Nguyen Van An', 'code' => 'E.g. EMP001', 'identity_number' => 'Enter identity number', 'phone' => 'Personal contact number', 'email' => 'Enter email', 'search' => 'Search employees...'],
    'options' => ['male' => 'Male', 'female' => 'Female', 'other' => 'Other', 'single' => 'Single', 'married' => 'Married', 'vietnam' => 'Vietnam', 'foreign' => 'Foreign'],
    'status' => ['working' => 'Working', 'on_leave' => 'On leave', 'resigned' => 'Resigned'],
    'table' => ['index' => '#', 'avatar' => 'AVATAR', 'code' => 'EMPLOYEE CODE', 'name' => 'FULL NAME', 'department' => 'DEPARTMENT', 'position' => 'POSITION', 'area' => 'AREA', 'kitchen' => 'KITCHEN', 'start_date' => 'START DATE', 'status' => 'STATUS', 'actions' => 'ACTIONS'],
    'actions' => ['create' => 'Add employee', 'save' => 'Save employee', 'update' => 'Update employee', 'cancel' => 'Cancel', 'view' => 'View details', 'edit' => 'Edit', 'export' => 'Export data'],
    'messages' => ['created' => 'Employee created successfully!', 'updated' => 'Employee updated successfully!', 'deleted' => 'Employee deleted successfully!', 'unnamed_document' => 'Unnamed document'],
    'upload' => ['hint' => 'Upload a JPG, PNG or WebP image. Maximum 2MB.', 'compact_hint' => 'JPG, PNG, WebP up to 2MB', 'uploading' => 'Uploading image...'],
    'validation' => ['code_required' => 'Employee code is required.', 'code_unique' => 'Employee code already exists.', 'name_required' => 'Full name is required.', 'email_required' => 'Email is required.', 'email_email' => 'Email format is invalid.', 'phone_required' => 'Phone number is required.', 'department_required' => 'Department is required.', 'position_required' => 'Position is required.', 'area_required' => 'Area is required.', 'start_date_required' => 'Start date is required.', 'avatar_image' => 'The profile image must be a JPG, PNG or WebP image.', 'avatar_max' => 'The profile image may not exceed 2MB.', 'document_mimes' => 'Attachments must be PDF, Word or image files.', 'document_max' => 'Attachments may not exceed 5MB.', 'document_expiry_date' => 'The document expiry date is invalid.'],
    'ui' => [
        'division_hint' => 'E.g. HR',
        'back' => 'Back to list', 'form_error' => 'There were errors; please check the form:', 'full_name' => 'Full legal name', 'internal_code' => 'Internal identifier', 'select_marital' => 'Select marital status', 'id_issue_place' => 'ID issuing authority', 'ethnicity_hint' => 'As shown in the employee record', 'religion_hint' => 'As shown in the employee record (if any)', 'permanent_hint' => 'As shown on the ID', 'current_address' => 'Current address', 'relationship' => 'Relationship', 'relationship_hint' => 'Father / Mother / Spouse...',
        'select_department' => 'Select department', 'division' => 'Division', 'select_position' => 'Select position', 'level' => 'Level', 'select_level' => 'Select level', 'employee_level' => 'Employee', 'specialist' => 'Specialist', 'team_leader' => 'Team leader', 'manager' => 'Manager', 'department_head' => 'Department head', 'employment_type' => 'Employment type', 'select_employment_type' => 'Select employment type', 'full_time' => 'Full-time', 'part_time' => 'Part-time', 'seasonal' => 'Seasonal', 'select_area' => 'Select area', 'no_kitchen' => 'None / Office', 'direct_manager' => 'Direct manager', 'select_manager' => 'Select manager', 'employee_status' => 'Employee status',
        'document_tracking' => 'Document tracking', 'document_help' => 'Enter a document name, attach a file and select its expiry date.', 'document_name' => 'Document name', 'attachment' => 'Attachment', 'expiry_date' => 'Expiry date', 'actions' => 'Actions', 'document_placeholder' => 'Document name (e.g. Employment contract)', 'choose_file' => 'Choose file', 'no_file' => 'No file', 'uploading' => 'Uploading...', 'delete_document' => 'Delete this document', 'add_document' => 'Add document', 'create_another' => 'Create another after saving',
        'subtitle' => 'Manage company employee information and records', 'total' => 'Total employees', 'expiring_documents' => 'Documents expiring soon', 'expires_within' => 'Expired or expiring within 30 days', 'all' => 'All', 'filters' => 'Filters', 'reset_filters' => 'Reset filters', 'confirm_delete' => 'Are you sure you want to delete this employee?', 'delete' => 'Delete employee', 'empty' => 'No employees found', 'empty_hint' => 'Try adjusting the filters or search terms.', 'pagination' => 'Showing :from to :to of :total employees', 'rows_per_page' => ':count rows/page',
    ],
];
