<?php

return [
    'navigation' => 'Timekeeping', 'group' => 'HUMAN RESOURCES', 'sections' => ['shift' => 'Work shift information', 'recorded_time' => 'Recorded time'],
    'fields' => ['employee' => 'Employee', 'date' => 'Work date', 'shift' => 'Work shift', 'check_in' => 'Check-in time', 'check_out' => 'Check-out time', 'overtime' => 'Overtime hours', 'status' => 'Status'],
    'status' => ['on_time' => 'On time', 'late' => 'Late', 'overtime' => 'Overtime', 'leave' => 'On leave', 'absent' => 'Absent', 'unrecorded' => 'Not recorded'],
    'table' => ['index' => '#', 'employee_code' => 'EMPLOYEE CODE', 'name' => 'FULL NAME', 'department' => 'DEPARTMENT', 'shift' => 'WORK SHIFT', 'check_in' => 'CHECK-IN', 'check_out' => 'CHECK-OUT', 'total' => 'TOTAL HOURS', 'overtime' => 'OVERTIME', 'status' => 'STATUS'],
    'actions' => ['export' => 'Export data', 'cancel' => 'Cancel', 'view' => 'View details', 'edit' => 'Edit'],
    'attendance' => ['not_assigned' => 'No shift assigned', 'recorded_at' => 'Recorded at :time', 'check_in_hint' => 'Click to check in', 'check_out_hint' => 'Click to check out', 'no_data' => 'No data', 'check_in_first' => 'Check in first', 'saved' => 'Time has been saved to the attendance record.', 'saved_today' => 'Time has been saved to the attendance system for :date.'],
    'messages' => ['created' => 'Timekeeping record created successfully!', 'updated' => 'Timekeeping record updated successfully!', 'deleted' => 'Timekeeping record deleted successfully.', 'employee_missing' => 'Employee information was not found.', 'linked_employee_missing' => 'No employee profile is linked to this account.', 'checked_in' => 'Checked in successfully at :time!', 'checked_out' => 'Checked out successfully at :time!'],
    'validation' => ['employee_required' => 'Employee is required.', 'employee_exists' => 'The selected employee is invalid.', 'date_required' => 'Work date is required.', 'shift_required' => 'Work shift is required.', 'shift_exists' => 'The selected shift is invalid.', 'check_in_format' => 'Check-in must use HH:MM format (e.g. 07:01).', 'check_out_format' => 'Check-out must use HH:MM format (e.g. 16:05).', 'status_required' => 'Status is required.'],
    'weekdays' => ['sunday' => 'Sunday', 'monday' => 'Monday', 'tuesday' => 'Tuesday', 'wednesday' => 'Wednesday', 'thursday' => 'Thursday', 'friday' => 'Friday', 'saturday' => 'Saturday'],
    'filters' => ['department' => 'Department', 'area' => 'Area'],
    'placeholders' => ['search' => 'Search employees...'],
    'ui' => ['edit_title' => 'Edit timekeeping record', 'create_title' => 'Add timekeeping record', 'edit_description' => 'Update employee work-hour details', 'create_description' => 'Create a manual timekeeping record', 'back' => 'Back to list', 'form_error' => 'There were errors; please check the form:', 'details' => 'Timekeeping details', 'save' => 'Save record', 'subtitle' => 'Track employee check-ins, check-outs, shifts and attendance', 'today' => 'Today', 'employee' => 'Employee', 'unknown' => 'Unknown', 'recorded_at' => 'Recorded at :time', 'filters' => 'Filters', 'reset_filters' => 'Reset filters', 'all' => 'All', 'actions' => 'Actions', 'confirm_delete' => 'Are you sure you want to delete this timekeeping record?', 'delete' => 'Delete timekeeping record', 'empty' => 'No timekeeping data found', 'empty_hint' => 'Try adjusting the filters or selecting another work date.', 'pagination' => 'Showing :from to :to of :total records', 'rows_per_page' => ':count rows/page', 'press_check_in' => 'Check in', 'press_check_out' => 'Check out', 'check_in_description' => 'Record the start of work', 'check_out_description' => 'Record the end of work', 'cannot_perform' => 'Not available'],
];
