<?php

return [
    'navigation' => 'Chấm công', 'group' => 'NHÂN SỰ',
    'sections' => ['shift' => 'Thông tin ca làm việc', 'recorded_time' => 'Thời gian ghi nhận'],
    'fields' => ['employee' => 'Nhân viên', 'date' => 'Ngày làm việc', 'shift' => 'Ca làm việc', 'check_in' => 'Giờ vào (Check-in)', 'check_out' => 'Giờ ra (Check-out)', 'overtime' => 'Số giờ tăng ca', 'status' => 'Trạng thái'],
    'status' => ['on_time' => 'Đúng giờ', 'late' => 'Đi trễ', 'overtime' => 'Tăng ca', 'leave' => 'Nghỉ phép', 'absent' => 'Vắng mặt', 'unrecorded' => 'Chưa ghi nhận'],
    'table' => ['index' => 'STT', 'employee_code' => 'MÃ NV', 'name' => 'HỌ VÀ TÊN', 'department' => 'PHÒNG BAN', 'shift' => 'CA LÀM VIỆC', 'check_in' => 'CHECK-IN', 'check_out' => 'CHECK-OUT', 'total' => 'TỔNG GIỜ', 'overtime' => 'TĂNG CA', 'status' => 'TRẠNG THÁI'],
    'actions' => ['export' => 'Xuất dữ liệu', 'cancel' => 'Hủy bỏ', 'view' => 'Xem chi tiết', 'edit' => 'Chỉnh sửa'],
    'attendance' => ['not_assigned' => 'Chưa phân ca', 'recorded_at' => 'Đã thực hiện lúc :time', 'check_in_hint' => 'Bấm để ghi nhận vào ca', 'check_out_hint' => 'Bấm để ghi nhận ra ca', 'no_data' => 'Chưa có dữ liệu', 'check_in_first' => 'Cần check-in trước', 'saved' => 'Thời gian đã được lưu vào bảng chấm công.', 'saved_today' => 'Thời gian đã được lưu vào hệ thống chấm công ngày :date.'],
    'messages' => ['created' => 'Thêm mới bản ghi chấm công thành công!', 'updated' => 'Cập nhật bản ghi chấm công thành công!', 'deleted' => 'Xóa bản ghi chấm công thành công.', 'employee_missing' => 'Không tìm thấy thông tin nhân sự.', 'linked_employee_missing' => 'Không tìm thấy thông tin nhân sự liên kết với tài khoản.', 'checked_in' => 'Check-in thành công lúc :time!', 'checked_out' => 'Check-out thành công lúc :time!'],
    'validation' => ['employee_required' => 'Nhân viên là bắt buộc.', 'employee_exists' => 'Nhân viên không hợp lệ.', 'date_required' => 'Ngày làm việc là bắt buộc.', 'shift_required' => 'Ca làm việc là bắt buộc.', 'shift_exists' => 'Ca làm việc không hợp lệ.', 'check_in_format' => 'Giờ vào phải theo định dạng HH:MM (VD: 07:01).', 'check_out_format' => 'Giờ ra phải theo định dạng HH:MM (VD: 16:05).', 'status_required' => 'Trạng thái là bắt buộc.'],
    'weekdays' => ['sunday' => 'Chủ Nhật', 'monday' => 'Thứ Hai', 'tuesday' => 'Thứ Ba', 'wednesday' => 'Thứ Tư', 'thursday' => 'Thứ Năm', 'friday' => 'Thứ Sáu', 'saturday' => 'Thứ Bảy'],
    'filters' => ['department' => 'Phòng ban', 'area' => 'Khu vực'],
    'placeholders' => ['search' => 'Tìm kiếm nhân viên...'],
    'ui' => ['edit_title' => 'Chỉnh sửa bản ghi chấm công', 'create_title' => 'Thêm bản ghi chấm công', 'edit_description' => 'Cập nhật thông tin chi tiết giờ công của nhân viên', 'create_description' => 'Tạo mới bản ghi chấm công thủ công cho nhân viên', 'back' => 'Quay lại danh sách', 'form_error' => 'Có lỗi xảy ra, vui lòng kiểm tra lại:', 'details' => 'Thông tin chi tiết chấm công', 'save' => 'Lưu bản ghi', 'subtitle' => 'Theo dõi check-in, check-out, ca làm việc và tình trạng đi làm của nhân viên', 'today' => 'Hôm nay', 'employee' => 'Nhân viên', 'unknown' => 'Chưa rõ', 'recorded_at' => 'Đã thực hiện lúc :time', 'filters' => 'Bộ lọc', 'reset_filters' => 'Cài lại bộ lọc', 'all' => 'Tất cả', 'actions' => 'Hành động', 'confirm_delete' => 'Bạn có chắc chắn muốn xóa bản ghi chấm công này?', 'delete' => 'Xóa chấm công', 'empty' => 'Không tìm thấy dữ liệu chấm công nào', 'empty_hint' => 'Hãy thử điều chỉnh bộ lọc hoặc chọn ngày làm việc khác.', 'pagination' => 'Hiển thị :from đến :to trong tổng số :total bản ghi', 'rows_per_page' => ':count dòng/trang', 'press_check_in' => 'Nhấn Check-in', 'press_check_out' => 'Nhấn Check-out', 'check_in_description' => 'Ghi nhận giờ bắt đầu làm', 'check_out_description' => 'Ghi nhận giờ kết thúc làm', 'cannot_perform' => 'Chưa thể thực hiện'],
];
